### ISSUE TITLE
点个赞，顺带提个新建议。

### ISSUE THREAD

**Issue by jozhi** [tjuking/storage#1]
这个方法刚好适合我现在的项目：同时可以本地存储和设置cookie；
然后就是其实还可以整一个阶梯式降级的解决方案，优先本地存储，然后cookie。

**Comment by tjuking** [comment]
@jozhi 谢谢你的点赞和建议，目前我遇到的业务场景暂时还用不到这样的方案，你可以fork再升级一下哈~
